# Generated by Django 4.2.3 on 2023-07-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation", old_name="data", new_name="date",
        ),
        migrations.AddField(
            model_name="patient",
            name="doctors",
            field=models.ManyToManyField(
                related_name="patients",
                through="hospital.Reservation",
                to="hospital.doctor",
            ),
        ),
    ]
